apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: elastic
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: my-filebeat
          mountPath: /usr/share/filebeat/my-file.log
          subPath: my-file.log
      volumes:
       - name: filebeat-config
         configMap:
           name: filebeat-configmap
       - name: my-filebeat
         configMap:
           name: my-filebeat

