apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elastic
data:
  logstash.conf: |
    input {
      file {
        path => "/usr/share/logstash/config/my-file.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "filebeat-test"
      }
    }
    
    
    